### ISSUE TITLE
为什么登录链接是中国科学技术大学的？

### ISSUE THREAD

**Issue by xiaomi2077** [yusanshi/ucas-checkin#1]
你是不是搞错2个学校的简称了？
![截屏-20211011110738-958x79](https://user-images.githubusercontent.com/33375652/136727943-97099a6e-d1be-4b91-9462-3db37535ce26.png)
![截屏-20211011110845-1920x1080](https://user-images.githubusercontent.com/33375652/136727983-106cfeb2-87ed-4f82-88c0-49274c1f383c.png)

**Comment by yusanshi** [comment]
抱歉给你造成了麻烦。这个**可能**是故意的，你懂的 :)

（tip: 我是中科大的）

**Comment by xiaomi2077** [comment]
我被钓了
